### PR TITLE
Generate static types

### PR DESCRIPTION
**Pull request by possibilities**
The motivation for this patch can be found [in this comment thread](https://github.com/seek-oss/playroom/issues/139#issuecomment-636430377). In a nutshell [playroom](https://github.com/seek-oss/playroom) cannot autocomplete props once the library has been built because it doesn't get props from `.d.ts` files (it gets them from exported interfaces in `tsx` files). So here we're taking the bluntest approach possible so that we can use this library in playroom from NPM without losing autocomplete:

1) We generate the property types ahead of time and store them in a json file in the repo
2) We use a [patched copy of playroom](https://github.com/possibilities/playroom/pull/1/files) anywhere we want to [consume this](https://github.com/possibilities/next-template/blob/master/playroom.config.js#L10)

### CODE REVIEW

**Comment by yinonov** [comment]
does this mean we can manually declare types/props for the autocomplete?

**Comment by possibilities** [comment]
You could

**Comment by possibilities** [comment]
The format is basically:

```
{
  Component: {
    nameOfProp: ['options', 'for', 'prop']
  }
}
```

I'll submit a PR upstream and see what happens.

**Comment by possibilities** [comment]
@yinonov I was going to submit a PR but got busy and now I'm conflicted. It would be nice to have but also, for me it sidesteps a problem that I think could be better addressed so I'm not sure I want to suggest this until I explore it more. As you can see though it's a small change, you're welcome to use it.

**Comment by yinonov** [comment]
Thank you, i'll look into that. in general it feels like a waste for playroom to focus on react patterns and needs this tweaking

**Comment by possibilities** [comment]
I understand where you're coming from. I think the counterargument might be that the idea of playroom is based around JSX so I'm unsure how far the non-react argument will go unless you're talking about other non-react libraries but still using JSX. Just playing devils advocate because I agree for other reasons that this would be a good addition. I wouldn't mind getting a slightly better idea how you're using it as I continue to think about the problems generally? You have a fork and you're supporting something other than JSX?

I'm personally also just starting to look into all of this but playroom is central to a lot of work I'm doing... initially I don't see responses from the maintainers and also see explicit comments from non-maintainers about the scarceness of maintainers' time... so I'm curious if it'll make sense to depend directly on it in the long term. I want to give them the benefit of the doubt and possibly work more closely with them to keep pushing forward on some things rather than accept it as-is or fork it (or replace it) so far... but keeping all avenues open.

**Comment by yinonov** [comment]
I think the most significant "competitor" for jsx nowadays is [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
That's what i'm using. I haven't given it all a deep architectural thinking but I'm using typescript and am predefining props. so guessing if tools such as [web-component-analyzer](https://github.com/runem/web-component-analyzer) are capable of extract proper analyzation then it's possible to lean on pre-generated autocomplete in playroom

**Comment by possibilities** [comment]
Very cool, thanks for the details.

**Pull request merged**
